# Generated by Django 2.2.4 on 2019-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='queued',
            field=models.BooleanField(default=True),
        ),
    ]
